[[plugins]]
package = "netlify-plugin-is-website-vulnerable"

[[redirects]]
  from = "obsidian.mikecarlson.io/*"
  to = "https://obsidian.mikecarlson.io/:splat"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

