[[plugins]]
package = "netlify-plugin-is-website-vulnerable"

[[redirects]]
  from = "/obsidian/*"
  to = "https://publish.obsidian.md/mtzfox/"
  status = 200
  force = true
  signed = "ce84b391-533a-4c5d-bea3-b5be73bb4f15"