[[plugins]]
package = "netlify-plugin-is-website-vulnerable"

[[redirects]]
  from = "https://publish.obsidian.md/mtzfox/*"
  to = "https://obsidian.mikecarlson.io/:splat"
  status = 301
  force = true