[[plugins]]
package = "netlify-plugin-is-website-vulnerable"

[[redirects]]
  from = "/obsidian"
  to = "https://obsidian.mikecarlson.io"
  status = 200
  force = true

[[redirects]]
  from = "https://publish.obsidian.md/mtzfox/*"
  to = "https://mikecarlson.io/obsidian/:splat"
  status = 200
  force = true