[[plugins]]
package = "netlify-plugin-is-website-vulnerable"

[[redirects]]
  from = "publish.obsidian.md/mtzfox/*"
  to = "https://mike-carlson.netlify.app/obsidian/:splat"
  status = 301
  force = true