[[plugins]]
package = "netlify-plugin-is-website-vulnerable"

[[redirects]]
  from = "https://obsidian.mikecarlson.io/*"
  to = "https://publish.obsidian.md/serve?url=obsidian.mikecarlson.io/"
  status = 200
  force = true

[[redirects]]
  from = "https://blog.mikecarlson.io/*"
  to = "https://publish.obsidian.md/serve?url=obsidian.mikecarlson.io/blog/:splat/"
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

