[[plugins]]
package = "netlify-plugin-is-website-vulnerable"

[[redirects]]
  from = "https://obsidian.mikecarlson.io"
  to = "https://publish.obsidian.md/mtzionfox/About+Me"
  status = 200
  force = true
  signed = "ce84b391-533a-4c5d-bea3-b5be73bb4f15"

[[redirects]]
  from = "/obsidian"
  to = "https://publish.obsidian.md/mtzionfox/About+Me/:splat"
  status = 200
  force = true
  signed = "ce84b391-533a-4c5d-bea3-b5be73bb4f15"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true