[[plugins]]
package = "netlify-plugin-is-website-vulnerable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/obsidian/*"
  to = "publish.obsidian.md/mtzfox/:splat"
  status = 200