[[plugins]]
package = "netlify-plugin-is-website-vulnerable"

[[redirects]]
  from = "https://obsidian.mikecarlson.io/*"
  to = "https://publish.obsidian.md/mtzfox/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "*/mtzfox/"
  to = "/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}