[[plugins]]
package = "netlify-plugin-is-website-vulnerable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://publish.obsidian.md/mtzfox/*"
  to = "https://mikecarlson.io/obsidian/:splat"
  status = 200
  force = true