[[plugins]]
package = "netlify-plugin-is-website-vulnerable"

[[redirects]]
  from = "https://obsidian.mikecarlson.io"
  to = "https://publish.obsidian.md/mtzionfox/About+Me"
  status = 200
  force = true

[[redirects]]
  from = "/obsidian"
  to = "https://publish.obsidian.md/mtzionfox/About+Me"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true