[[plugins]]
package = "netlify-plugin-is-website-vulnerable"

[[redirects]]
  from = "https://obsidian.mikecarlson.io/*"
  to = "https://publish.obsidian.md/mtzfox/:splat"
  status = 301
  force = true
  headers = {X-From = "Netlify"}