[[redirects]]
  from = "https://obsidian.mikecarlson.io"
  to = "https://publish.obsidian.md/mtzionfox/About+Me"
  status = 301
  force = true

[[redirects]]
  from = "/obsidian"
  to = "https://publish.obsidian.md/mtzionfox/About+Me"
  status = 301
  force = true # that we always redirect


[[redirects]]
  from = "https://somenetlifysite.netlify.app"
  to = "https://mycustomdomain.com"
  status = 301
  force = true